; This file in left completely blank intentionally

; It is a placeholder for a file that will be generated by the Python scripts, but in
; case the user decides to not run that part of the script, AutoHotKey needs the file
; to exist to not display an error message if the file is #Include'd
